# Generated by Django 4.2.3 on 2024-04-15 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_description', models.CharField(max_length=128)),
                ('max_guests', models.IntegerField()),
                ('room_reserved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ZooTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('ticket_used', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('guests', models.IntegerField()),
                ('booking_in', models.DateTimeField()),
                ('booking_out', models.DateTimeField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_portal.hotelroom')),
            ],
        ),
    ]
