# Generated by Django 4.2.3 on 2024-04-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_alter_zooticket_entry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='account_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='zooticket',
            old_name='account_id',
            new_name='user',
        ),
    ]
